apiVersion: v1
kind: Service
metadata:
  name: nexabudget-be-svc
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: nexabudget-be
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
